###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ra01)
#  Generated on:      Thu Jan 22 17:23:17 2026
#  Design:            counter
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2.000ns) in timing_config constraints_fast([syn_opt_counter.functional_wcl_fast.sdc])
#   clk (period 6.000ns) in timing_config constraints_slow([syn_opt_counter.functional_wcl_slow.sdc])
#   clk (period 4.000ns) in timing_config constraints_typ([syn_opt_counter.functional_wcl_typical.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:constraints_fast (sdc syn_opt_counter.functional_wcl_fast.sdc)
create_ccopt_skew_group -name clk/constraints_fast -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/constraints_fast true
set_ccopt_property extracted_from_clock_name -skew_group clk/constraints_fast clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/constraints_fast constraints_fast
set_ccopt_property extracted_from_delay_corners -skew_group clk/constraints_fast dalay_corner_fast

# Skew group to balance non generated clock:clk in timing_config:constraints_slow (sdc syn_opt_counter.functional_wcl_slow.sdc)
create_ccopt_skew_group -name clk/constraints_slow -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/constraints_slow true
set_ccopt_property extracted_from_clock_name -skew_group clk/constraints_slow clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/constraints_slow constraints_slow
set_ccopt_property extracted_from_delay_corners -skew_group clk/constraints_slow delay_corner_slow

# Skew group to balance non generated clock:clk in timing_config:constraints_typ (sdc syn_opt_counter.functional_wcl_typical.sdc)
create_ccopt_skew_group -name clk/constraints_typ -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/constraints_typ true
set_ccopt_property extracted_from_clock_name -skew_group clk/constraints_typ clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/constraints_typ constraints_typ
set_ccopt_property extracted_from_delay_corners -skew_group clk/constraints_typ delay_corner_tpy


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

