/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ra01)
#  Generated on:      Thu Jan 22 17:28:23 2026
#  Design:            counter
#  Command:           saveNetlist counter_postRoute_physical.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 22 2026 16:39:08 IST (Jan 22 2026 11:09:08 UTC)
// Verification Directory fv/counter 
module RC_CG_MOD_AUTO_counter (
	ck_in, 
	enable, 
	test, 
	ck_out);
   input ck_in;
   input enable;
   input test;
   output ck_out;

   // Internal wires
   wire UNCONNECTED;
   wire enl;
   wire n_0;

   AND2X1 g16__2398 (.A(enl),
	.B(ck_in),
	.Y(ck_out));
   TLATNX1 enl_reg (.D(n_0),
	.GN(ck_in),
	.Q(enl),
	.QN(UNCONNECTED));
   OR2X2 g18__5107 (.A(enable),
	.B(test),
	.Y(n_0));
endmodule

module counter (
	reset, 
	clk, 
	count);
   input reset;
   input clk;
   output [7:0] count;

   // Internal wires
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire rc_gclk;

   RC_CG_MOD_AUTO_counter RC_CG_HIER_INST1 (.ck_in(clk),
	.enable(count[0]),
	.test(1'b0),
	.ck_out(rc_gclk));
   JKFFRXL \count_reg[7]  (.J(n_10),
	.K(n_10),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[7]),
	.QN(UNCONNECTED0));
   DFFRX1 \count_reg[6]  (.D(n_11),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[6]),
	.QN(UNCONNECTED1));
   AOI2BB1X1 g177__6260 (.A0N(n_8),
	.A1N(count[6]),
	.B0(n_10),
	.Y(n_11));
   DFFRX1 \count_reg[5]  (.D(n_9),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[5]),
	.QN(UNCONNECTED2));
   AND2X2 g179__4319 (.A(n_8),
	.B(count[6]),
	.Y(n_10));
   AOI2BB1X1 g180__8428 (.A0N(n_6),
	.A1N(count[5]),
	.B0(n_8),
	.Y(n_9));
   DFFRX1 \count_reg[4]  (.D(n_7),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[4]),
	.QN(UNCONNECTED3));
   AND2X2 g182__5526 (.A(n_6),
	.B(count[5]),
	.Y(n_8));
   AOI2BB1X1 g183__6783 (.A0N(n_4),
	.A1N(count[4]),
	.B0(n_6),
	.Y(n_7));
   DFFRX1 \count_reg[3]  (.D(n_5),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[3]),
	.QN(UNCONNECTED4));
   AND2X2 g185__3680 (.A(n_4),
	.B(count[4]),
	.Y(n_6));
   AOI2BB1X1 g186__1617 (.A0N(n_2),
	.A1N(count[3]),
	.B0(n_4),
	.Y(n_5));
   DFFRX1 \count_reg[2]  (.D(n_3),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[2]),
	.QN(UNCONNECTED5));
   AND2X2 g188__2802 (.A(n_2),
	.B(count[3]),
	.Y(n_4));
   AOI2BB1X1 g189__1705 (.A0N(n_1),
	.A1N(count[2]),
	.B0(n_2),
	.Y(n_3));
   AND2X2 g190__5122 (.A(n_1),
	.B(count[2]),
	.Y(n_2));
   DFFRX1 \count_reg[0]  (.D(n_12),
	.CK(clk),
	.RN(n_0),
	.Q(count[0]),
	.QN(n_12));
   AND2X2 g192__8246 (.A(count[1]),
	.B(count[0]),
	.Y(n_1));
   DFFRX1 \count_reg[1]  (.D(n_13),
	.CK(rc_gclk),
	.RN(n_0),
	.Q(count[1]),
	.QN(n_13));
   CLKINVX3 g194 (.A(reset),
	.Y(n_0));
endmodule

