/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ra01)
#  Generated on:      Wed Jan 21 12:21:00 2026
#  Design:            simple_alu
#  Command:           saveNetlist simple_alu_power.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 20 2026 15:32:09 IST (Jan 20 2026 10:02:09 UTC)
// Verification Directory fv/simple_alu 
module full_adder (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g83__2398 (.A(cin),
	.B(a),
	.CI(b),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_95 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5107 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_94 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6260 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_93 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__4319 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_92 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__8428 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_91 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5526 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_90 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6783 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_89 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__3680 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_88 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__1617 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_87 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__2802 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_86 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__1705 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_85 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5122 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_84 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__8246 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_83 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__7098 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_82 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6131 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_81 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__1881 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_80 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5115 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_79 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__7482 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_78 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__4733 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_77 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6161 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_76 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__9315 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_75 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__9945 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_74 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__2883 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_73 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__2346 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_72 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__1666 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_71 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__7410 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_70 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6417 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_69 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5477 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_68 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__2398 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_67 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__5107 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_66 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX4 g75__6260 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module full_adder_65 (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFHX1 g75__4319 (.A(a),
	.B(b),
	.CI(cin),
	.CO(cout),
	.S(sum));
endmodule

module simple_alu (
	A, 
	B, 
	ALUControl, 
	Result, 
	zero, 
	Cout);
   input [31:0] A;
   input [31:0] B;
   input [1:0] ALUControl;
   output [31:0] Result;
   output zero;
   output Cout;

   // Internal wires
   wire [31:0] Sum;
   wire [32:0] I1_carry;
   wire [31:0] B_input;
   wire n_0;
   wire n_1;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_147;
   wire n_148;
   wire n_258;
   wire n_259;

   full_adder I1_INST0 (.a(A[0]),
	.b(n_258),
	.cin(ALUControl[0]),
	.sum(Sum[0]),
	.cout(I1_carry[1]));
   full_adder_95 I1_INST1 (.a(A[1]),
	.b(n_259),
	.cin(I1_carry[1]),
	.sum(Sum[1]),
	.cout(I1_carry[2]));
   full_adder_94 I1_INST2 (.a(A[2]),
	.b(B_input[2]),
	.cin(I1_carry[2]),
	.sum(Sum[2]),
	.cout(I1_carry[3]));
   full_adder_93 I1_INST3 (.a(A[3]),
	.b(B_input[3]),
	.cin(I1_carry[3]),
	.sum(Sum[3]),
	.cout(I1_carry[4]));
   full_adder_92 I1_INST4 (.a(A[4]),
	.b(B_input[4]),
	.cin(I1_carry[4]),
	.sum(Sum[4]),
	.cout(I1_carry[5]));
   full_adder_91 I1_INST5 (.a(A[5]),
	.b(B_input[5]),
	.cin(I1_carry[5]),
	.sum(Sum[5]),
	.cout(I1_carry[6]));
   full_adder_90 I1_INST6 (.a(A[6]),
	.b(B_input[6]),
	.cin(I1_carry[6]),
	.sum(Sum[6]),
	.cout(I1_carry[7]));
   full_adder_89 I1_INST7 (.a(A[7]),
	.b(B_input[7]),
	.cin(I1_carry[7]),
	.sum(Sum[7]),
	.cout(I1_carry[8]));
   full_adder_88 I1_INST8 (.a(A[8]),
	.b(B_input[8]),
	.cin(I1_carry[8]),
	.sum(Sum[8]),
	.cout(I1_carry[9]));
   full_adder_87 I1_INST9 (.a(A[9]),
	.b(B_input[9]),
	.cin(I1_carry[9]),
	.sum(Sum[9]),
	.cout(I1_carry[10]));
   full_adder_86 I1_INST10 (.a(A[10]),
	.b(B_input[10]),
	.cin(I1_carry[10]),
	.sum(Sum[10]),
	.cout(I1_carry[11]));
   full_adder_85 I1_INST11 (.a(A[11]),
	.b(B_input[11]),
	.cin(I1_carry[11]),
	.sum(Sum[11]),
	.cout(I1_carry[12]));
   full_adder_84 I1_INST12 (.a(A[12]),
	.b(B_input[12]),
	.cin(I1_carry[12]),
	.sum(Sum[12]),
	.cout(I1_carry[13]));
   full_adder_83 I1_INST13 (.a(A[13]),
	.b(B_input[13]),
	.cin(I1_carry[13]),
	.sum(Sum[13]),
	.cout(I1_carry[14]));
   full_adder_82 I1_INST14 (.a(A[14]),
	.b(B_input[14]),
	.cin(I1_carry[14]),
	.sum(Sum[14]),
	.cout(I1_carry[15]));
   full_adder_81 I1_INST15 (.a(A[15]),
	.b(B_input[15]),
	.cin(I1_carry[15]),
	.sum(Sum[15]),
	.cout(I1_carry[16]));
   full_adder_80 I1_INST16 (.a(A[16]),
	.b(B_input[16]),
	.cin(I1_carry[16]),
	.sum(Sum[16]),
	.cout(I1_carry[17]));
   full_adder_79 I1_INST17 (.a(A[17]),
	.b(B_input[17]),
	.cin(I1_carry[17]),
	.sum(Sum[17]),
	.cout(I1_carry[18]));
   full_adder_78 I1_INST18 (.a(A[18]),
	.b(B_input[18]),
	.cin(I1_carry[18]),
	.sum(Sum[18]),
	.cout(I1_carry[19]));
   full_adder_77 I1_INST19 (.a(A[19]),
	.b(B_input[19]),
	.cin(I1_carry[19]),
	.sum(Sum[19]),
	.cout(I1_carry[20]));
   full_adder_76 I1_INST20 (.a(A[20]),
	.b(B_input[20]),
	.cin(I1_carry[20]),
	.sum(Sum[20]),
	.cout(I1_carry[21]));
   full_adder_75 I1_INST21 (.a(A[21]),
	.b(B_input[21]),
	.cin(I1_carry[21]),
	.sum(Sum[21]),
	.cout(I1_carry[22]));
   full_adder_74 I1_INST22 (.a(A[22]),
	.b(B_input[22]),
	.cin(I1_carry[22]),
	.sum(Sum[22]),
	.cout(I1_carry[23]));
   full_adder_73 I1_INST23 (.a(A[23]),
	.b(B_input[23]),
	.cin(I1_carry[23]),
	.sum(Sum[23]),
	.cout(I1_carry[24]));
   full_adder_72 I1_INST24 (.a(A[24]),
	.b(B_input[24]),
	.cin(I1_carry[24]),
	.sum(Sum[24]),
	.cout(I1_carry[25]));
   full_adder_71 I1_INST25 (.a(A[25]),
	.b(B_input[25]),
	.cin(I1_carry[25]),
	.sum(Sum[25]),
	.cout(I1_carry[26]));
   full_adder_70 I1_INST26 (.a(A[26]),
	.b(B_input[26]),
	.cin(I1_carry[26]),
	.sum(Sum[26]),
	.cout(I1_carry[27]));
   full_adder_69 I1_INST27 (.a(A[27]),
	.b(B_input[27]),
	.cin(I1_carry[27]),
	.sum(Sum[27]),
	.cout(I1_carry[28]));
   full_adder_68 I1_INST28 (.a(A[28]),
	.b(B_input[28]),
	.cin(I1_carry[28]),
	.sum(Sum[28]),
	.cout(I1_carry[29]));
   full_adder_67 I1_INST29 (.a(A[29]),
	.b(B_input[29]),
	.cin(I1_carry[29]),
	.sum(Sum[29]),
	.cout(I1_carry[30]));
   full_adder_66 I1_INST30 (.a(A[30]),
	.b(B_input[30]),
	.cin(I1_carry[30]),
	.sum(Sum[30]),
	.cout(I1_carry[31]));
   full_adder_65 I1_INST31 (.a(A[31]),
	.b(B_input[31]),
	.cin(I1_carry[31]),
	.sum(Sum[31]),
	.cout(Cout));
   CLKINVX4 g2010 (.A(Sum[0]),
	.Y(n_148));
   CLKINVX4 g2011 (.A(Sum[1]),
	.Y(n_147));
   CLKXOR2X2 g2034__8428 (.A(ALUControl[0]),
	.B(B[2]),
	.Y(B_input[2]));
   CLKXOR2X2 g1972__5526 (.A(ALUControl[0]),
	.B(B[3]),
	.Y(B_input[3]));
   CLKXOR2X2 g1973__6783 (.A(ALUControl[0]),
	.B(B[4]),
	.Y(B_input[4]));
   CLKXOR2X2 g1974__3680 (.A(ALUControl[0]),
	.B(B[5]),
	.Y(B_input[5]));
   CLKXOR2X2 g1975__1617 (.A(ALUControl[0]),
	.B(B[6]),
	.Y(B_input[6]));
   CLKXOR2X2 g1976__2802 (.A(ALUControl[0]),
	.B(B[7]),
	.Y(B_input[7]));
   CLKXOR2X2 g1977__1705 (.A(ALUControl[0]),
	.B(B[8]),
	.Y(B_input[8]));
   CLKXOR2X2 g1978__5122 (.A(ALUControl[0]),
	.B(B[9]),
	.Y(B_input[9]));
   CLKXOR2X2 g1979__8246 (.A(ALUControl[0]),
	.B(B[10]),
	.Y(B_input[10]));
   CLKXOR2X2 g1980__7098 (.A(ALUControl[0]),
	.B(B[11]),
	.Y(B_input[11]));
   CLKXOR2X2 g1981__6131 (.A(ALUControl[0]),
	.B(B[12]),
	.Y(B_input[12]));
   CLKXOR2X2 g1982__1881 (.A(ALUControl[0]),
	.B(B[13]),
	.Y(B_input[13]));
   CLKXOR2X2 g1983__5115 (.A(ALUControl[0]),
	.B(B[14]),
	.Y(B_input[14]));
   CLKXOR2X2 g1984__7482 (.A(ALUControl[0]),
	.B(B[15]),
	.Y(B_input[15]));
   CLKXOR2X2 g1985__4733 (.A(ALUControl[0]),
	.B(B[16]),
	.Y(B_input[16]));
   CLKXOR2X2 g1986__6161 (.A(ALUControl[0]),
	.B(B[17]),
	.Y(B_input[17]));
   CLKXOR2X2 g1987__9315 (.A(ALUControl[0]),
	.B(B[18]),
	.Y(B_input[18]));
   CLKXOR2X2 g1988__9945 (.A(ALUControl[0]),
	.B(B[19]),
	.Y(B_input[19]));
   NOR4BX4 g5312__2883 (.AN(n_123),
	.B(Result[29]),
	.C(Result[30]),
	.D(Result[31]),
	.Y(zero));
   NOR4X8 g5313__2346 (.A(n_122),
	.B(Result[26]),
	.C(Result[27]),
	.D(Result[28]),
	.Y(n_123));
   OR4X6 g5314__1666 (.A(n_121),
	.B(Result[23]),
	.C(Result[24]),
	.D(Result[25]),
	.Y(n_122));
   OR4X6 g5315__7410 (.A(n_120),
	.B(Result[20]),
	.C(Result[21]),
	.D(Result[22]),
	.Y(n_121));
   OR4X6 g5316__6417 (.A(n_119),
	.B(Result[17]),
	.C(Result[18]),
	.D(Result[19]),
	.Y(n_120));
   OR4X6 g5317__5477 (.A(n_118),
	.B(Result[14]),
	.C(Result[15]),
	.D(Result[16]),
	.Y(n_119));
   OR4X6 g5318__2398 (.A(n_117),
	.B(Result[11]),
	.C(Result[12]),
	.D(Result[13]),
	.Y(n_118));
   OR4X6 g5319__5107 (.A(n_116),
	.B(Result[8]),
	.C(Result[9]),
	.D(Result[10]),
	.Y(n_117));
   OR4X6 g5320__6260 (.A(n_115),
	.B(Result[5]),
	.C(Result[6]),
	.D(Result[7]),
	.Y(n_116));
   OR4X6 g5321__4319 (.A(Result[0]),
	.B(Result[1]),
	.C(n_114),
	.D(Result[4]),
	.Y(n_115));
   OR2X6 g5322__8428 (.A(Result[2]),
	.B(Result[3]),
	.Y(n_114));
   OAI2BB1X4 g5323__5526 (.A0N(n_1),
	.A1N(Sum[15]),
	.B0(n_101),
	.Y(Result[15]));
   OAI221X4 g5324__6783 (.A0(n_32),
	.A1(n_33),
	.B0(ALUControl[1]),
	.B1(n_147),
	.C0(n_73),
	.Y(Result[1]));
   OAI221X4 g5325__3680 (.A0(n_30),
	.A1(n_33),
	.B0(ALUControl[1]),
	.B1(n_0),
	.C0(n_75),
	.Y(Result[2]));
   OAI2BB1X4 g5326__1617 (.A0N(n_1),
	.A1N(Sum[18]),
	.B0(n_108),
	.Y(Result[18]));
   OAI2BB1X4 g5327__2802 (.A0N(n_1),
	.A1N(Sum[5]),
	.B0(n_110),
	.Y(Result[5]));
   OAI2BB1X4 g5328__1705 (.A0N(n_1),
	.A1N(Sum[4]),
	.B0(n_107),
	.Y(Result[4]));
   OAI2BB1X4 g5329__5122 (.A0N(n_1),
	.A1N(Sum[3]),
	.B0(n_106),
	.Y(Result[3]));
   OAI2BB1X4 g5330__8246 (.A0N(n_1),
	.A1N(Sum[31]),
	.B0(n_112),
	.Y(Result[31]));
   OAI2BB1X4 g5331__7098 (.A0N(n_1),
	.A1N(Sum[24]),
	.B0(n_103),
	.Y(Result[24]));
   OAI2BB1X4 g5332__6131 (.A0N(n_1),
	.A1N(Sum[17]),
	.B0(n_104),
	.Y(Result[17]));
   OAI2BB1X4 g5333__1881 (.A0N(n_1),
	.A1N(Sum[28]),
	.B0(n_105),
	.Y(Result[28]));
   OAI2BB1X4 g5334__5115 (.A0N(n_1),
	.A1N(Sum[16]),
	.B0(n_102),
	.Y(Result[16]));
   OAI2BB1X4 g5335__7482 (.A0N(n_1),
	.A1N(Sum[25]),
	.B0(n_109),
	.Y(Result[25]));
   OAI2BB1X4 g5336__4733 (.A0N(n_1),
	.A1N(Sum[27]),
	.B0(n_98),
	.Y(Result[27]));
   OAI2BB1X4 g5337__6161 (.A0N(n_1),
	.A1N(Sum[23]),
	.B0(n_113),
	.Y(Result[23]));
   OAI221X4 g5338__9315 (.A0(n_31),
	.A1(n_33),
	.B0(ALUControl[1]),
	.B1(n_148),
	.C0(n_78),
	.Y(Result[0]));
   OAI2BB1X4 g5339__9945 (.A0N(n_1),
	.A1N(Sum[6]),
	.B0(n_100),
	.Y(Result[6]));
   OAI2BB1X4 g5340__2883 (.A0N(n_1),
	.A1N(Sum[22]),
	.B0(n_96),
	.Y(Result[22]));
   OAI2BB1X4 g5341__2346 (.A0N(n_1),
	.A1N(Sum[13]),
	.B0(n_97),
	.Y(Result[13]));
   OAI2BB1X4 g5342__1666 (.A0N(n_1),
	.A1N(Sum[30]),
	.B0(n_111),
	.Y(Result[30]));
   OAI2BB1X4 g5343__7410 (.A0N(n_1),
	.A1N(Sum[29]),
	.B0(n_99),
	.Y(Result[29]));
   OAI2BB1X4 g5344__6417 (.A0N(n_1),
	.A1N(Sum[12]),
	.B0(n_95),
	.Y(Result[12]));
   OAI2BB1X4 g5345__5477 (.A0N(n_1),
	.A1N(Sum[11]),
	.B0(n_94),
	.Y(Result[11]));
   OAI2BB1X4 g5346__2398 (.A0N(n_1),
	.A1N(Sum[26]),
	.B0(n_90),
	.Y(Result[26]));
   OAI2BB1X4 g5347__5107 (.A0N(n_1),
	.A1N(Sum[21]),
	.B0(n_93),
	.Y(Result[21]));
   OAI2BB1X4 g5348__6260 (.A0N(n_1),
	.A1N(Sum[10]),
	.B0(n_91),
	.Y(Result[10]));
   OAI2BB1X4 g5349__4319 (.A0N(n_1),
	.A1N(Sum[20]),
	.B0(n_88),
	.Y(Result[20]));
   OAI2BB1X4 g5350__8428 (.A0N(n_1),
	.A1N(Sum[9]),
	.B0(n_89),
	.Y(Result[9]));
   OAI2BB1X4 g5351__5526 (.A0N(n_1),
	.A1N(Sum[8]),
	.B0(n_87),
	.Y(Result[8]));
   OAI2BB1X4 g5352__6783 (.A0N(n_1),
	.A1N(Sum[19]),
	.B0(n_85),
	.Y(Result[19]));
   OAI2BB1X4 g5353__3680 (.A0N(n_1),
	.A1N(Sum[7]),
	.B0(n_86),
	.Y(Result[7]));
   OAI2BB1X4 g5354__1617 (.A0N(n_1),
	.A1N(Sum[14]),
	.B0(n_92),
	.Y(Result[14]));
   AOI31X4 g5355__2802 (.A0(ALUControl[1]),
	.A1(B[23]),
	.A2(A[23]),
	.B0(n_66),
	.Y(n_113));
   AOI31X4 g5356__1705 (.A0(ALUControl[1]),
	.A1(B[31]),
	.A2(A[31]),
	.B0(n_65),
	.Y(n_112));
   AOI31X4 g5357__5122 (.A0(ALUControl[1]),
	.A1(B[30]),
	.A2(A[30]),
	.B0(n_53),
	.Y(n_111));
   AOI31X4 g5358__8246 (.A0(ALUControl[1]),
	.A1(B[5]),
	.A2(A[5]),
	.B0(n_81),
	.Y(n_110));
   AOI31X4 g5359__7098 (.A0(ALUControl[1]),
	.A1(B[25]),
	.A2(A[25]),
	.B0(n_77),
	.Y(n_109));
   AOI31X4 g5360__6131 (.A0(ALUControl[1]),
	.A1(B[18]),
	.A2(A[18]),
	.B0(n_79),
	.Y(n_108));
   AOI31X4 g5361__1881 (.A0(ALUControl[1]),
	.A1(B[4]),
	.A2(A[4]),
	.B0(n_80),
	.Y(n_107));
   AOI31X4 g5362__5115 (.A0(ALUControl[1]),
	.A1(B[3]),
	.A2(A[3]),
	.B0(n_76),
	.Y(n_106));
   AOI31X4 g5363__7482 (.A0(ALUControl[1]),
	.A1(B[28]),
	.A2(A[28]),
	.B0(n_71),
	.Y(n_105));
   AOI31X4 g5364__4733 (.A0(ALUControl[1]),
	.A1(B[17]),
	.A2(A[17]),
	.B0(n_74),
	.Y(n_104));
   AOI31X4 g5365__6161 (.A0(ALUControl[1]),
	.A1(B[24]),
	.A2(A[24]),
	.B0(n_70),
	.Y(n_103));
   AOI31X4 g5366__9315 (.A0(ALUControl[1]),
	.A1(B[16]),
	.A2(A[16]),
	.B0(n_72),
	.Y(n_102));
   AOI31X4 g5367__9945 (.A0(ALUControl[1]),
	.A1(B[15]),
	.A2(A[15]),
	.B0(n_84),
	.Y(n_101));
   AOI31X4 g5368__2883 (.A0(ALUControl[1]),
	.A1(B[6]),
	.A2(A[6]),
	.B0(n_69),
	.Y(n_100));
   AOI31X4 g5369__2346 (.A0(ALUControl[1]),
	.A1(B[29]),
	.A2(A[29]),
	.B0(n_82),
	.Y(n_99));
   AOI31X4 g5370__1666 (.A0(ALUControl[1]),
	.A1(B[27]),
	.A2(A[27]),
	.B0(n_61),
	.Y(n_98));
   AOI31X4 g5371__7410 (.A0(ALUControl[1]),
	.A1(B[13]),
	.A2(A[13]),
	.B0(n_64),
	.Y(n_97));
   AOI31X4 g5372__6417 (.A0(ALUControl[1]),
	.A1(B[22]),
	.A2(A[22]),
	.B0(n_62),
	.Y(n_96));
   AOI31X4 g5373__5477 (.A0(ALUControl[1]),
	.A1(B[12]),
	.A2(A[12]),
	.B0(n_63),
	.Y(n_95));
   AOI31X4 g5374__2398 (.A0(ALUControl[1]),
	.A1(B[11]),
	.A2(A[11]),
	.B0(n_60),
	.Y(n_94));
   AOI31X4 g5375__5107 (.A0(ALUControl[1]),
	.A1(B[21]),
	.A2(A[21]),
	.B0(n_58),
	.Y(n_93));
   AOI31X4 g5376__6260 (.A0(ALUControl[1]),
	.A1(B[14]),
	.A2(A[14]),
	.B0(n_67),
	.Y(n_92));
   AOI31X4 g5377__4319 (.A0(ALUControl[1]),
	.A1(B[10]),
	.A2(A[10]),
	.B0(n_59),
	.Y(n_91));
   AOI31X4 g5378__8428 (.A0(ALUControl[1]),
	.A1(B[26]),
	.A2(A[26]),
	.B0(n_68),
	.Y(n_90));
   AOI31X4 g5379__5526 (.A0(ALUControl[1]),
	.A1(B[9]),
	.A2(A[9]),
	.B0(n_57),
	.Y(n_89));
   AOI31X4 g5380__6783 (.A0(ALUControl[1]),
	.A1(B[20]),
	.A2(A[20]),
	.B0(n_55),
	.Y(n_88));
   AOI31X4 g5381__3680 (.A0(ALUControl[1]),
	.A1(B[8]),
	.A2(A[8]),
	.B0(n_56),
	.Y(n_87));
   AOI31X4 g5382__1617 (.A0(ALUControl[1]),
	.A1(B[7]),
	.A2(A[7]),
	.B0(n_54),
	.Y(n_86));
   AOI31X4 g5383__2802 (.A0(ALUControl[1]),
	.A1(B[19]),
	.A2(A[19]),
	.B0(n_83),
	.Y(n_85));
   AOI2BB1X4 g5384__1705 (.A0N(B[15]),
	.A1N(A[15]),
	.B0(n_33),
	.Y(n_84));
   AOI2BB1X4 g5385__5122 (.A0N(B[19]),
	.A1N(A[19]),
	.B0(n_33),
	.Y(n_83));
   AOI2BB1X4 g5386__8246 (.A0N(B[29]),
	.A1N(A[29]),
	.B0(n_33),
	.Y(n_82));
   AOI2BB1X4 g5387__7098 (.A0N(B[5]),
	.A1N(A[5]),
	.B0(n_33),
	.Y(n_81));
   AOI2BB1X4 g5388__6131 (.A0N(B[4]),
	.A1N(A[4]),
	.B0(n_33),
	.Y(n_80));
   AOI2BB1X4 g5389__1881 (.A0N(B[18]),
	.A1N(A[18]),
	.B0(n_33),
	.Y(n_79));
   NAND3X8 g5390__5115 (.A(ALUControl[1]),
	.B(B[0]),
	.C(A[0]),
	.Y(n_78));
   AOI2BB1X4 g5391__7482 (.A0N(B[25]),
	.A1N(A[25]),
	.B0(n_33),
	.Y(n_77));
   AOI2BB1X4 g5392__4733 (.A0N(B[3]),
	.A1N(A[3]),
	.B0(n_33),
	.Y(n_76));
   NAND3X8 g5393__6161 (.A(ALUControl[1]),
	.B(B[2]),
	.C(A[2]),
	.Y(n_75));
   AOI2BB1X4 g5394__9315 (.A0N(B[17]),
	.A1N(A[17]),
	.B0(n_33),
	.Y(n_74));
   NAND3X8 g5395__9945 (.A(ALUControl[1]),
	.B(B[1]),
	.C(A[1]),
	.Y(n_73));
   AOI2BB1X4 g5396__2883 (.A0N(B[16]),
	.A1N(A[16]),
	.B0(n_33),
	.Y(n_72));
   AOI2BB1X4 g5397__2346 (.A0N(B[28]),
	.A1N(A[28]),
	.B0(n_33),
	.Y(n_71));
   AOI2BB1X4 g5398__1666 (.A0N(B[24]),
	.A1N(A[24]),
	.B0(n_33),
	.Y(n_70));
   AOI2BB1X4 g5399__7410 (.A0N(B[6]),
	.A1N(A[6]),
	.B0(n_33),
	.Y(n_69));
   AOI2BB1X4 g5400__6417 (.A0N(B[26]),
	.A1N(A[26]),
	.B0(n_33),
	.Y(n_68));
   AOI2BB1X2 g5401__5477 (.A0N(B[14]),
	.A1N(A[14]),
	.B0(n_33),
	.Y(n_67));
   AOI2BB1X4 g5402__2398 (.A0N(B[23]),
	.A1N(A[23]),
	.B0(n_33),
	.Y(n_66));
   AOI2BB1X4 g5403__5107 (.A0N(B[31]),
	.A1N(A[31]),
	.B0(n_33),
	.Y(n_65));
   AOI2BB1X4 g5404__6260 (.A0N(B[13]),
	.A1N(A[13]),
	.B0(n_33),
	.Y(n_64));
   AOI2BB1X4 g5405__4319 (.A0N(B[12]),
	.A1N(A[12]),
	.B0(n_33),
	.Y(n_63));
   AOI2BB1X4 g5406__8428 (.A0N(B[22]),
	.A1N(A[22]),
	.B0(n_33),
	.Y(n_62));
   AOI2BB1X4 g5407__5526 (.A0N(B[27]),
	.A1N(A[27]),
	.B0(n_33),
	.Y(n_61));
   AOI2BB1X4 g5408__6783 (.A0N(B[11]),
	.A1N(A[11]),
	.B0(n_33),
	.Y(n_60));
   AOI2BB1X4 g5409__3680 (.A0N(B[10]),
	.A1N(A[10]),
	.B0(n_33),
	.Y(n_59));
   AOI2BB1X4 g5410__1617 (.A0N(B[21]),
	.A1N(A[21]),
	.B0(n_33),
	.Y(n_58));
   AOI2BB1X4 g5411__2802 (.A0N(B[9]),
	.A1N(A[9]),
	.B0(n_33),
	.Y(n_57));
   AOI2BB1X4 g5412__1705 (.A0N(B[8]),
	.A1N(A[8]),
	.B0(n_33),
	.Y(n_56));
   AOI2BB1X4 g5413__5122 (.A0N(B[20]),
	.A1N(A[20]),
	.B0(n_33),
	.Y(n_55));
   AOI2BB1X4 g5414__8246 (.A0N(B[7]),
	.A1N(A[7]),
	.B0(n_33),
	.Y(n_54));
   AOI2BB1X4 g5415__7098 (.A0N(B[30]),
	.A1N(A[30]),
	.B0(n_33),
	.Y(n_53));
   NOR2X8 g5435__6131 (.A(B[1]),
	.B(A[1]),
	.Y(n_32));
   NAND2X8 g5436__1881 (.A(ALUControl[0]),
	.B(ALUControl[1]),
	.Y(n_33));
   NOR2X8 g5437__5115 (.A(B[0]),
	.B(A[0]),
	.Y(n_31));
   NOR2X8 g5438__7482 (.A(B[2]),
	.B(A[2]),
	.Y(n_30));
   CLKINVX2 g5466 (.A(ALUControl[1]),
	.Y(n_1));
   CLKINVX4 g5468 (.A(Sum[2]),
	.Y(n_0));
   CLKXOR2X2 g1989__4733 (.A(ALUControl[0]),
	.B(B[20]),
	.Y(B_input[20]));
   CLKXOR2X2 g1990__6161 (.A(ALUControl[0]),
	.B(B[21]),
	.Y(B_input[21]));
   CLKXOR2X2 g1991__9315 (.A(ALUControl[0]),
	.B(B[22]),
	.Y(B_input[22]));
   CLKXOR2X2 g1992__9945 (.A(ALUControl[0]),
	.B(B[23]),
	.Y(B_input[23]));
   CLKXOR2X2 g1993__2883 (.A(ALUControl[0]),
	.B(B[24]),
	.Y(B_input[24]));
   CLKXOR2X2 g1994__2346 (.A(ALUControl[0]),
	.B(B[25]),
	.Y(B_input[25]));
   CLKXOR2X2 g1995__1666 (.A(ALUControl[0]),
	.B(B[26]),
	.Y(B_input[26]));
   CLKXOR2X2 g1996__7410 (.A(ALUControl[0]),
	.B(B[27]),
	.Y(B_input[27]));
   CLKXOR2X2 g1997__6417 (.A(ALUControl[0]),
	.B(B[28]),
	.Y(B_input[28]));
   CLKXOR2X2 g1998__5477 (.A(ALUControl[0]),
	.B(B[29]),
	.Y(B_input[29]));
   CLKXOR2X2 g1999__2398 (.A(ALUControl[0]),
	.B(B[30]),
	.Y(B_input[30]));
   CLKXOR2X2 g2000__5107 (.A(ALUControl[0]),
	.B(B[31]),
	.Y(B_input[31]));
   XOR2X4 g2__6260 (.A(B[0]),
	.B(ALUControl[0]),
	.Y(n_258));
   XOR2X4 g5493__4319 (.A(B[1]),
	.B(ALUControl[0]),
	.Y(n_259));
endmodule

